POST http://localhost:9898/signup
Content-Type: application/json

{
    "username":"user",
    "password":"1234"
}

###
POST http://localhost:9898/signin
Content-Type: application/json

{
    "username":"user",
    "password":"1234"
}

###
POST http://localhost:9898/auth/access
Content-Type: application/json

{
    "accessToken":"eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJFeHBpcmVBdCI6MTYyNDM1Njc3NCwiUGFzc3dvcmQiOiIkMmEkMDUkT2laSFVLQ2w0ME4zMmJzNk9NUXNxdWx1WE5mSjdQdWhLU0tOS3Exc3BIaGR0bXl6OHU1UTYiLCJVc2VybmFtZSI6InVzZXIifQ.Fj5jjwZYnrIXBOdSIx574ENt_kzNWg6eqe31ViGIe4Xc4in-VTGnaQ6jByyR1-lg"
}

###
POST http://localhost:9898/auth/refresh
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJFeHBpcmVBdCI6MTYyNDM1NzM3NCwiUGFzc3dvcmQiOiIkMmEkMDUkT2laSFVLQ2w0ME4zMmJzNk9NUXNxdWx1WE5mSjdQdWhLU0tOS3Exc3BIaGR0bXl6OHU1UTYiLCJVc2VybmFtZSI6InVzZXIifQ.-Z_pQCuzPOby9ETq24uclLvywyqxbUZlSZGN1NbmpK-i1P0PZSNMKiC068awXTMb"
}